### ISSUE TITLE
Heart Rate Chart v1.0

### ISSUE THREAD

**Issue by herkulano** [RADAR-CNS/RADAR-Dashboard#10]
- [x] add chart structure for heart-rate data
- [x] add service and store for heart-rate data
- [x] plot [avg, median] data values to chart-heart-rate
- [ ] plot [min, max] data values to chart-heart-rate

**Comment by herkulano** [comment]
We need to define the Heart Rate schema:
https://github.com/RADAR-CNS/RADAR-Schemas/pull/7

**Comment by kerzmaximilian** [comment]
Yep! Lets wait on a decision for that until after the call tomorrow. Amos organised a schema-devoted TC. I'll send you invite via Slack.

**Comment by herkulano** [comment]
Items moved to next iteration:
* plot [min, max] data values to chart-heart-rate

**Comment by herkulano** [comment]
Next iteration: #18
