### ISSUE TITLE
Implement Study view

### ISSUE THREAD

**Issue by petcupaula** [RADAR-CNS/RADAR-Dashboard#122]
We need to finalise the table implementation (#14, #85, #86) and the status component (#15).

Also to consider: 

- showing demographics data (gender, year of birth)
- handling user access to multiple studies

**Comment by herkulano** [comment]
Latest design of the Study view:
![desktop 300-study](https://cloud.githubusercontent.com/assets/125300/23798208/35c6f974-05ac-11e7-9f4a-339e8b830a61.png)
