### ISSUE TITLE
Implement list/table component

### ISSUE THREAD

**Issue by kerzmaximilian** [RADAR-CNS/RADAR-Dashboard#14]
Suggesting to split list component into two components:

- [ ] Row component
- [ ] List component

Does that make sense?

**Comment by herkulano** [comment]
@kerzmaximilian yes, it does make sense. 

Although I suggest we use a Data Table component:
- [angular2-data-table](http://swimlane.github.io/angular2-data-table/) // [demo](http://swimlane.github.io/angular2-data-table/)
- [angular-2-data-table](https://github.com/ggmod/angular-2-data-table) // [demo](https://ggmod.github.io/angular-2-data-table-demo)
- [ng2-table](https://github.com/valor-software/ng2-table) // [demo](http://valor-software.com/ng2-table/)
- **(not ready)** [MD2 / Data Table](https://github.com/angular/material2/issues/581)

**Comment by kerzmaximilian** [comment]
Amazing! Wasn't aware they already implemented that!

**Comment by petcupaula** [comment]
Agree that we can use an already implemented Data Table (or Data Grid) component. Here are a few others that could be interesting:
* [ag-grid](https://github.com/ceolter/ag-grid-ng2) // [demo](https://www.ag-grid.com/best-angular-2-data-grid/)
* [ng2-handsontable](https://github.com/valor-software/ng2-handsontable) // [demo](http://valor-software.com/ng2-handsontable/)

**Comment by herkulano** [comment]
I'm leaning towards [ngx-datatable](https://github.com/swimlane/ngx-datatable)

It can be simple, but it has advanced features if needed.

Some of the features that stand out:
* Handle large data sets ( Virtual DOM )
* Decoupled theme'ing with included Google Material theme
* Light codebase / No external dependencies
* AoT Compilation Support
