### ISSUE TITLE
Settings: Configure Questionnaires

### ISSUE THREAD

**Issue by kerzmaximilian** [RADAR-CNS/RADAR-Dashboard#144]
Administrators of the questionnaires should be able to allocate groups of questionnaires to distinct subsets of patients via the platform administration

**Comment by afolarin** [comment]
@kerzmaximilian participant groups/subsets should be arbitrarily definable groups (with the default group being member of project/study).  Ideally it would be possible to group participants based on the their metadata (e.g. uses device XX, is member of control arm etc)
