### ISSUE TITLE
Implement workbook component

### ISSUE THREAD

**Issue by petcupaula** [RADAR-CNS/RADAR-Dashboard#16]
Proposing that we need to define a new type of component that is able to handle multiple tabs/pages of grids. 

If charts are part of tiles, tiles are configured in a grid, and a grid is added in a dashboard, then multiple dashboards (i.e. multiple tabs with the same general focus and audience) could be grouped in a workbook.

**Comment by kerzmaximilian** [comment]
Really good point! Lets define it a bit more in our call now!
