### ISSUE TITLE
Study view: Patient Cohort Table

### ISSUE THREAD

**Issue by kerzmaximilian** [RADAR-CNS/RADAR-Dashboard#225]
To be implemented:

- [x] Pull paginator-bar to the bottom of tile.

- [ ] Instead of intra-row scroll to display multiple sources, implement tip-box (hovering over row) to display individual connectedness. Within row, show summary connectedness status (see sketch file).

**Comment by mpgxvii** [comment]
Where can I get the data for the individual connectedness?
