### ISSUE TITLE
Subject: Set resolution based on time frame

### ISSUE THREAD

**Issue by herkulano** [RADAR-CNS/RADAR-Dashboard#306]
Based on the selected time frame we should limit the resolution of the charts. For example, for a dataset of a week, the maximum resolution should be `ONE_DAY`.

The data for the charts should also be fetched only for the current zoom level.

**Comment by blootsvoets** [comment]
FYI: in the REST API we are also implementing a similar auto-resolution method if no resolution is given, aiming to always return about 100 frames.
