### ISSUE TITLE
Subject: Remove sorting when the API is ready 

### ISSUE THREAD

**Issue by herkulano** [RADAR-CNS/RADAR-Dashboard#308]
https://github.com/RADAR-base/RADAR-Dashboard/blob/1c4ae4c5a0606322e0ba9fca5e9e26782df39582/src/app/subject/services/sensors-data.service.ts#L69

Remove the sorting from the line above when this issue is closed
https://github.com/RADAR-base/RADAR-RestApi/issues/108

**Comment by mpgxvii** [comment]
Solved in #319
