### ISSUE TITLE
Participant Management Dashboard

### ISSUE THREAD

**Issue by afolarin** [RADAR-CNS/RADAR-Dashboard#4]
We will need an interface to manage participants that are sending data into the platform. 

The platform dashboard(s) should initially include participant:
- enrolment
- device remote configuration
- removal
- monitoring data upload compliance

**Comment by herkulano** [comment]
Regarding the enrollment of patients is this done by the researcher or by the patient, i.e., do patients have a separate enrollment form application? If so could this be part of the Questionnaire application?

**Comment by afolarin** [comment]
@herkulano 
> Regarding the enrollment of patients is this done by the researcher or by the patient, i.e., do patients have a separate enrollment form application? If so could this be part of the Questionnaire application?

There are other "crowd sourced" research use cases where participants might download the app and self-enrol but I as far as I'm aware this is't something being considered by RADAR-CNS.

The typical clinical trial or research cohort scenario will be enrolment by some research/administrative staff who will manage enrolment, monitor compliance etc.

**Comment by afolarin** [comment]
Also related RADAR-CNS/RADAR-AndroidApplication#11

**Comment by herkulano** [comment]
Relates to https://github.com/RADAR-CNS/RADAR-Questionnaire/issues/6
