### ISSUE TITLE
Create Dockerized RADAR-Dashboard

### ISSUE THREAD

**Issue by afolarin** [RADAR-CNS/RADAR-Dashboard#44]
Create a fb489aec9f0643cb1405b0a8701feeb4c42eb9ec  Dockerfile in this repo for the RADAR-Dashboard based on the default node container https://hub.docker.com/_/node/ deploy the dashboard. Needed for RADAR-CNS/RADAR-Docker#11

/cc @kerzmaximilian

**Comment by afolarin** [comment]
Tested, seems ok. Have added an automated build to https://hub.docker.com/r/radarcns/radar-dashboard/, I'll update the docker/README.md slight name change which is derived from the git repo. should trigger a rebuild when master is pushed to.

**Comment by herkulano** [comment]
Changed to nginx for a better server and yarn for faster and more reliable node modules install.

RADAR-CNS/RADAR-Docker#11
