### ISSUE TITLE
ngx-datatable styling and scroll vertical

### ISSUE THREAD

**Issue by kerzmaximilian** [RADAR-CNS/RADAR-Dashboard#85]

**Comment by herkulano** [comment]
Latest design of the Study view with the data table:

![desktop 300-study](https://cloud.githubusercontent.com/assets/125300/23798729/8f72d090-05ae-11e7-9157-c2935175f002.png)

https://github.com/RADAR-CNS/RADAR-Design/tree/master/Screens
