### ISSUE TITLE
table service implementation

### ISSUE THREAD

**Issue by kerzmaximilian** [RADAR-CNS/RADAR-Dashboard#86]
@herkulano your advice needed: via rxjs store or keep data decoupled from store?

**Comment by herkulano** [comment]
@kerzmaximilian Both have pros and cons, my thoughts...

Using the store we can have the data for all tiles managed in the "state.grid", in this way the components would be managed by the container.

The state would look something like this, without normalizing it:
```js
{
  grid: [{
      id: "6c84fb90-12c4-11e1-840d-7b25c5ee775a",
      cols: 3,
      rows: 2,
      title: "Heart Rate Monitoring",
      type: "heart-rate",
      data: [
        ...
      ],
      config: {
        ...
      }
    },
    ...
  ],
  ...
}
```

On the other hand, the tiles can be self-contained and manage their own state.

Using the store can be over-engineering sometimes. It really depends if the state of the tiles/components is going to be modified or shared outside them. If not then it's simpler to have the state of the components managed by the components.

Another advantaged of the store is if the management of the state of the dynamic dashboard is also done by the server. For example, if we want to allow users to build their dashboards and save the state of the dashboard on the server. If so, then it could be better to use the store.

/cc @petcupaula @MaximMoinat
